"""URDF + PyBullet checks for the FarmHand rail-SCARA (Fix-B build).

Run: python sim/sim_check.py  -> urdf/farmhand_scara.urdf, sim/SIM_REPORT.md
1. Inverse dynamics on the worst J1 move (180° in 2.2 s, arm stretched, 1.5 kg) vs (a) an analytic I·α with the
   same masses (checks the URDF) and (b) the Phase-1 hand calc (rule: sim within ~15 %, hand calc higher).
2. Hold test: gravity torque on J1, J2, W must be ~0 (vertical axes); Z holds the whole arm's weight.
3. Static sag (beam theory, sim/stiffness.py) because a rigid-body sim cannot bend.
"""
import math
import os
import sys

import pybullet as pb

HERE = os.path.dirname(__file__)
sys.path.insert(0, os.path.join(HERE, "..", "cad"))
sys.path.insert(0, HERE)
from params import L1, L2  # noqa: E402
import stiffness  # noqa: E402

l1, l2, man = L1 / 1000, L2 / 1000, 0.06
# (name, mass kg, com xyz in the link frame) — Fix-B masses, ASSUMED until weighed
LINKS = {
    "z_carriage": (1.0, (0, -0.03, 0)),
    "upper_arm": (1.05, (0.19, 0, 0.09)),           # printed box + 2 alu tubes + J2 motor at the elbow
    "forearm": (0.70, (0.10, 0, -0.02)),
    "hand": (0.41 + 1.5, (0.0, 0.0, -0.05)),         # hand + payload (payload CG 60 mm out handled below)
}
PAYLOAD_OFF = man


def inertial(m, c, r=0.03):
    i = 0.4 * m * r * r
    return (f'<inertial><origin xyz="{c[0]} {c[1]} {c[2]}"/><mass value="{m}"/>'
            f'<inertia ixx="{i}" iyy="{i}" izz="{i}" ixy="0" ixz="0" iyz="0"/></inertial>')


def urdf():
    hand_m = LINKS["hand"][0]
    hand_c = (1.5 * PAYLOAD_OFF / hand_m, 0, -0.05)   # payload sits 60 mm out along the hand
    return f"""<?xml version="1.0"?>
<robot name="farmhand_scara">
  <link name="world_base"><inertial><mass value="0"/><inertia ixx="0" iyy="0" izz="0" ixy="0" ixz="0" iyz="0"/></inertial></link>
  <link name="x_carriage">{inertial(8.0, (0, 0, 0.4))}</link>
  <joint name="X" type="prismatic"><parent link="world_base"/><child link="x_carriage"/><axis xyz="1 0 0"/>
    <limit lower="0" upper="1.3" effort="200" velocity="0.5"/></joint>
  <link name="z_carriage">{inertial(*LINKS["z_carriage"])}</link>
  <joint name="Z" type="prismatic"><parent link="x_carriage"/><child link="z_carriage"/><origin xyz="0 0 0.2"/><axis xyz="0 0 1"/>
    <limit lower="0" upper="0.9" effort="500" velocity="0.02"/></joint>
  <link name="upper_arm">{inertial(*LINKS["upper_arm"])}</link>
  <joint name="J1" type="revolute"><parent link="z_carriage"/><child link="upper_arm"/><axis xyz="0 0 1"/>
    <limit lower="-2.618" upper="2.618" effort="10" velocity="2"/></joint>
  <link name="forearm">{inertial(*LINKS["forearm"])}</link>
  <joint name="J2" type="revolute"><parent link="upper_arm"/><child link="forearm"/><origin xyz="{l1} 0 0"/><axis xyz="0 0 1"/>
    <limit lower="-2.53" upper="2.53" effort="5" velocity="2"/></joint>
  <link name="hand">{inertial(hand_m, hand_c, 0.02)}</link>
  <joint name="W" type="revolute"><parent link="forearm"/><child link="hand"/><origin xyz="{l2} 0 0"/><axis xyz="0 0 1"/>
    <limit lower="-3.14" upper="3.14" effort="3" velocity="3"/></joint>
</robot>
"""


def main():
    os.makedirs(os.path.join(HERE, "..", "urdf"), exist_ok=True)
    path = os.path.join(HERE, "..", "urdf", "farmhand_scara.urdf")
    open(path, "w").write(urdf())

    pb.connect(pb.DIRECT)
    pb.setGravity(0, 0, -9.81)
    rid = pb.loadURDF(path, useFixedBase=True)
    nj = pb.getNumJoints(rid)
    names = [pb.getJointInfo(rid, i)[1].decode() for i in range(nj)]

    # 1. J1 worst move: triangular velocity profile, 180° in 2.2 s -> alpha = 4θ/t²
    alpha = 4 * math.pi / 2.2 ** 2
    q = [0.5, 0.4, 0.0, 0.0, 0.0]
    tau_acc = pb.calculateInverseDynamics(rid, q, [0, 0, 1.0, 0, 0], [0, 0, alpha, 0, 0])
    tau_still = pb.calculateInverseDynamics(rid, q, [0] * 5, [0] * 5)
    j1_sim = tau_acc[2]

    # analytic I about J1 with the same point masses (+ the tiny link spheres)
    ua_m, ua_c = LINKS["upper_arm"]
    fa_m, fa_c = LINKS["forearm"]
    h_m = LINKS["hand"][0]
    hand_cx = l1 + l2 + 1.5 * PAYLOAD_OFF / h_m
    sph = lambda m, r=0.03: 0.4 * m * r * r
    I_an = (ua_m * (ua_c[0] ** 2 + ua_c[1] ** 2) + sph(ua_m) + fa_m * (l1 + fa_c[0]) ** 2 + sph(fa_m)
            + h_m * hand_cx ** 2 + sph(h_m, 0.02))
    j1_an = I_an * alpha
    sys.path.insert(0, os.path.join(HERE, "..", "design"))
    j1_hand = 2.58            # design/phase1_torque_pass.md, lean variant (includes 0.5 N·m friction)

    lines = ["# FarmHand rail-SCARA — simulation report (generated by `sim/sim_check.py`)\n",
             f"URDF: `urdf/farmhand_scara.urdf` (joints {', '.join(names)}); PyBullet {pb.getAPIVersion()} inverse dynamics. "
             "Masses are the Fix-B build estimates (ASSUMED until parts are weighed).\n",
             "## 1. Worst J1 move: 180° in 2.2 s, arm stretched, 1.5 kg\n",
             "| Source | J1 torque (N·m) |", "|---|---|",
             f"| PyBullet inverse dynamics | {j1_sim:.2f} |",
             f"| Analytic I·α, same masses (checks the URDF) | {j1_an:.2f} ({100 * (j1_sim - j1_an) / j1_an:+.1f} %) |",
             f"| Phase-1 hand calc incl. 0.5 N·m friction | {j1_hand:.2f} |",
             f"\nSim is {100 * j1_sim / j1_hand:.0f} % of the hand calc → hand calc is higher (conservative) "
             f"{'✓' if j1_sim <= j1_hand else '✗'}; gap = the 0.5 N·m friction allowance + rounder Phase-1 masses. "
             f"Capacity (NEMA 17, 1:16 belt, 24 V derate): 4.26 N·m → sim load **{100 * j1_sim / 4.26:.0f} %**, "
             f"hand-calc load {100 * j1_hand / 4.26:.0f} % (rule ≤ 70 %).\n",
             "## 2. Hold test (arm stretched, 1.5 kg, gravity only)\n",
             "| Joint | Holding torque / force | Note |", "|---|---|---|",
             f"| J1 | {tau_still[2]:.4f} N·m | vertical axis: gravity goes into the bearings |",
             f"| J2 | {tau_still[3]:.4f} N·m | vertical axis |",
             f"| W | {tau_still[4]:.4f} N·m | vertical axis |",
             f"| Z | {tau_still[1]:.1f} N | carried by the self-locking T8×2 screw, motor off |",
             f"| X | {tau_still[0]:.2f} N | horizontal |",
             "\nSo the only gravity load in the whole robot is Z, and the screw holds it with no power: "
             "R7 \"no stalled-motor holds\" is met by construction.\n",
             stiffness.report()]
    out = os.path.join(HERE, "SIM_REPORT.md")
    open(out, "w").write("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
